version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: []

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: []
