FROM node:16-alpine

# Mandatory arguments
ARG DATABASE_URL
ARG DB_URL
ARG NEXT_PUBLIC_RSA_PUBLIC_KEY

EXPOSE 3000

WORKDIR /app

COPY . .

RUN yarn

ENV DATABASE_URL=$DATABASE_URL
ENV NODE_ENV=production

RUN yarn build

ENV DB_URL=$DB_URL
ENV IS_DOCKER=true
ENV NEXT_PUBLIC_RSA_PUBLIC_KEY=$NEXT_PUBLIC_RSA_PUBLIC_KEY
ENV NEXT_PUBLIC_NODE_ENV=$NODE_ENV

ENTRYPOINT [ "yarn", "start" ]
