version: "3.9"

services:
  db:
    container_name: tell_me_db
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_USER_USERNAME: ${MONGO_USER_USERNAME}
      MONGO_INITDB_USER_PASSWORD: ${MONGO_USER_PASSWORD}
    volumes:
      - ./scripts/docker/init_mongo.sh:/docker-entrypoint-initdb.d/init_mongo.sh
      - mongodb-data:/data/db

  app:
    container_name: tell_me_app
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    restart: always
    environment:
        DB_URL: mongodb://${MONGO_USER_USERNAME}:${MONGO_USER_PASSWORD}@db:27017/${MONGO_DATABASE}
        NODE_ENV: ${NODE_ENV}
        RSA_PRIVATE_KEY: ${RSA_PRIVATE_KEY}
    ports:
      - ${PORT}:80
    depends_on:
      - db

volumes:
  mongodb-data:
